#!/bin/sh

# restart dwm without logging out or closing applications
# orginal snippet - https://wiki.archlinux.org/title/dwm

while true; do
    # Log stderror to a file 
    dwm 2> ~/.dwm.log
    # No error logging
    # dwm >/dev/null 2>&1
done
